import { buttons } from "globals/settings/buttons";
import { sectionGlobals } from "globals/settings/section-globals";
import { fontTypeRange } from "globals/settings/type-range";

export const contentBlocks = {
  labels: {
    type: "labels",
    name: "Labels",
    settings: [
      {
        type: "textarea" as const,
        id: "labels",
        label: "Labels",
        info: "Comma Separated List",
      },
      {
        type: "range" as const,
        id: "opacity",
        label: "Opacity",
        default: 100,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "header" as const,
        content: "Layout",
      },
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "radio" as const,
        id: "label__style",
        label: "Style",
        default: "bg-primary-bg text-primary-text",
        options: [
          {
            value: "bg-primary-bg text-primary-text",
            label: "Primary",
          },
          {
            value: "bg-primary-text text-primary-bg",
            label: "Primary Inverted",
          },
          {
            value: "bg-secondary-bg text-secondary-text",
            label: "Secondary",
          },
        ],
      },
      sectionGlobals.maxWidth,
      sectionGlobals.responsiveVisibility,
    ],
  },
  text: {
    type: "text",
    name: "Text",
    settings: [
      {
        type: "richtext" as const,
        id: "title",
        label: "Content",
        info: "Supports type text metafield access on Global Objects (Product, Article, Collection, Page, Shop, Blog) via [object.namespace.field] placeholder",
      },
      fontTypeRange({ id: "title_font", label: "Font Group" }),
      {
        type: "range" as const,
        id: "opacity",
        label: "Opacity",
        default: 100,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "header" as const,
        content: "Alignment",
      },
      {
        type: "select" as const,
        id: "alignment_desktop",
        label: "Desktop Text Alignment",
        default: "[text-align:inherit]",
        options: [
          {
            value: "[text-align:inherit]",
            label: "Inherit",
          },
          {
            value: "text-left",
            label: "Left",
          },
          {
            value: "text-center",
            label: "Center",
          },
          {
            value: "text-right",
            label: "Right",
          },
        ],
      },
      {
        type: "select" as const,
        id: "alignment_mobile",
        label: "Mobile Text Alignment",
        default: "max-md:[text-align:inherit]",
        options: [
          {
            value: "max-md:[text-align:inherit]",
            label: "Inherit",
          },
          {
            value: "max-md:text-left",
            label: "Left",
          },
          {
            value: "max-md:text-center",
            label: "Center",
          },
          {
            value: "max-md:text-right",
            label: "Right",
          },
        ],
      },
      {
        type: "header" as const,
        content: "Layout",
      },
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },

      sectionGlobals.maxWidth,
      sectionGlobals.responsiveVisibility,
    ],
  },
  typewriter: {
    type: "typewriter",
    name: "Typewriter Text",
    settings: [
      {
        type: "header" as const,
        content: "Styling & Fix Content",
      },
      {
        type: "richtext" as const,
        id: "content",
        label: "Base Content",
        default: "<p>Prefixed content:</p><p>[content]</p>" as const,
        info: "Use [content] as Typewriter Effect Placeholder",
      },
      fontTypeRange({ id: "content_font", label: "Font Group" }),
      {
        type: "header" as const,
        content: "Content",
      },
      {
        type: "textarea" as const,
        id: "text_1",
        label: "Text 1",
      },
      {
        type: "textarea" as const,
        id: "text_2",
        label: "Text 2",
      },
      {
        type: "textarea" as const,
        id: "text_3",
        label: "Text 3",
      },
      {
        type: "textarea" as const,
        id: "text_4",
        label: "Text 4",
      },
      {
        type: "textarea" as const,
        id: "text_5",
        label: "Text 5",
      },
      {
        type: "textarea" as const,
        id: "text_6",
        label: "Text 6",
      },
      {
        type: "header" as const,
        content: "Typewriter Effect",
      },
      {
        type: "range" as const,
        id: "speed",
        label: "Speed",
        default: 30,
        min: 1,
        max: 100,
        step: 1,
        unit: "%",
      },
      {
        type: "range" as const,
        id: "delay",
        label: "Delay",
        default: 2,
        min: 1,
        max: 10,
        step: 0.1,
        unit: "s",
      },
      {
        type: "header" as const,
        content: "Styling",
      },
      {
        type: "range" as const,
        id: "opacity",
        label: "Opacity",
        default: 100,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "color" as const,
        id: "color",
        label: "Color",
        default: "#000000",
      },
      {
        type: "header" as const,
        content: "Alignment",
      },
      {
        type: "select" as const,
        id: "alignment_desktop",
        label: "Desktop Text Alignment",
        default: "[text-align:inherit]",
        options: [
          {
            value: "[text-align:inherit]",
            label: "Inherit",
          },
          {
            value: "text-left",
            label: "Left",
          },
          {
            value: "text-center",
            label: "Center",
          },
          {
            value: "text-right",
            label: "Right",
          },
        ],
      },
      {
        type: "select" as const,
        id: "alignment_mobile",
        label: "Mobile Text Alignment",
        default: "max-md:[text-align:inherit]",
        options: [
          {
            value: "max-md:[text-align:inherit]",
            label: "Inherit",
          },
          {
            value: "max-md:text-left",
            label: "Left",
          },
          {
            value: "max-md:text-center",
            label: "Center",
          },
          {
            value: "max-md:text-right",
            label: "Right",
          },
        ],
      },
      {
        type: "range" as const,
        id: "min_height",
        label: "Min_height",
        default: 0,
        min: 0,
        max: 500,
        step: 5,
        unit: "px",
        info: "Set a min height if the height of the text blocks is not consistent.",
      },
      {
        type: "header" as const,
        content: "Layout",
      },
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },

      sectionGlobals.maxWidth,
      sectionGlobals.responsiveVisibility,
    ],
  },
  page: {
    type: "page",
    name: "Page",
    settings: [
      {
        type: "page" as const,
        id: "page",
        label: "Page",
      },
      fontTypeRange({ id: "title_font", label: "Font Group" }),
      {
        type: "range" as const,
        id: "opacity",
        label: "Opacity",
        default: 100,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "header" as const,
        content: "Layout",
      },
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      sectionGlobals.maxWidth,
      sectionGlobals.responsiveVisibility,
    ],
  },
  features: {
    type: "features",
    name: "Feature List",
    settings: [
      {
        type: "header" as const,
        content: "Feature 1",
      },
      {
        type: "image_picker" as const,
        id: "icon_1",
        label: "Icon",
      },
      {
        type: "richtext" as const,
        id: "content_1",
        label: "Content",
      },
      fontTypeRange({ id: "content_font_1", label: "Font Group" }),
      {
        type: "paragraph" as const,
        content: " ",
      },
      {
        type: "header" as const,
        content: "Feature 2",
      },
      {
        type: "image_picker" as const,
        id: "icon_2",
        label: "Icon",
      },
      {
        type: "richtext" as const,
        id: "content_2",
        label: "Content",
      },
      fontTypeRange({ id: "content_font_2", label: "Font Group" }),
      {
        type: "paragraph" as const,
        content: " ",
      },
      {
        type: "header" as const,
        content: "Feature 3",
      },
      {
        type: "image_picker" as const,
        id: "icon_3",
        label: "Icon",
      },
      {
        type: "richtext" as const,
        id: "content_3",
        label: "Content",
      },
      fontTypeRange({ id: "content_font_3", label: "Font Group" }),
      {
        type: "paragraph" as const,
        content: " ",
      },
      {
        type: "header" as const,
        content: "Feature 4",
      },
      {
        type: "image_picker" as const,
        id: "icon_4",
        label: "Icon",
      },
      {
        type: "richtext" as const,
        id: "content_4",
        label: "Content",
      },
      fontTypeRange({ id: "content_font_4", label: "Font Group" }),
      {
        type: "paragraph" as const,
        content: " ",
      },
      {
        type: "paragraph" as const,
        content: " ",
      },
      {
        type: "header" as const,
        content: "Layout",
      },
      {
        type: "range" as const,
        id: "icon_size",
        label: "Icon Size",
        default: 40,
        min: 20,
        max: 120,
        step: 1,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "spacing",
        label: "Spacing",
        default: 0,
        min: 0,
        max: 100,
        step: 1,
        unit: "px",
      },
      sectionGlobals.align__horizontal,
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      sectionGlobals.maxWidth,
      sectionGlobals.responsiveVisibility,
    ],
  },
  image: {
    type: "image",
    name: "Inline Image",
    settings: [
      {
        type: "image_picker" as const,
        id: "image",
        label: "Image",
      },
      {
        type: "range" as const,
        id: "height",
        label: "Height",
        default: 80,
        min: 20,
        max: 400,
        step: 5,
        unit: "px",
      },
      {
        type: "header" as const,
        content: "Layout",
      },
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      sectionGlobals.responsiveVisibility,
    ],
  },
  accentLine: {
    type: "accent_line",
    name: "Accent line",
    settings: [
      {
        type: "color" as const,
        id: "color",
        label: "Color",
      },
      {
        type: "range" as const,
        id: "height",
        label: "height",
        default: 2,
        min: 1,
        max: 8,
        step: 1,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "width",
        label: "Width",
        default: 30,
        min: 5,
        max: 280,
        step: 5,
        unit: "px",
      },
      {
        type: "header" as const,
        content: "Layout",
      },
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      sectionGlobals.maxWidth,
      sectionGlobals.responsiveVisibility,
    ],
  },
  buttonGroup: {
    type: "buttons",
    name: "Buttons",
    settings: [
      ...buttons.primary,
      ...buttons.secondary,
      {
        type: "header" as const,
        content: "Layout",
      },

      {
        type: "radio" as const,
        id: "button__mobile_layout",
        label: "Mobile Button Layout",
        default: "flex max-md:flex-col max-md:w-full",
        options: [
          {
            value: "flex",
            label: "Fit Space",
          },
          {
            value: "flex max-md:flex-col max-md:w-full",
            label: "Fullwidth",
          },
        ],
      },
      {
        type: "radio" as const,
        id: "button__desktop_layout",
        label: "Desktop Button Layout",
        default: "flex",
        options: [
          {
            value: "flex",
            label: "Fit Space",
          },
          {
            value: "flex md:!flex-col md:w-full",
            label: "Fullwidth",
          },
        ],
      },
      {
        type: "range" as const,
        id: "margin_top",
        label: "Margin Top",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      {
        type: "range" as const,
        id: "margin_bottom",
        label: "Margin Bottom",
        default: 0,
        min: -12,
        max: 128,
        step: 2,
        unit: "px",
      },
      { ...sectionGlobals.maxWidth, default: "max-w-full" },
      sectionGlobals.responsiveVisibility,
    ],
  },
};
