export const iconList = {
  type: "select" as const,
  id: "icon_list",
  label: "Icon List",
  default: "check-square-broken",
  options: [
    {
      value: "none",
      label: "None",
    },
    { value: "activity", label: "activity" },
    { value: "alert-circle", label: "alert-circle" },
    { value: "announcement", label: "announcement" },
    { value: "arrow-narrow-left", label: "arrow-narrow-left" },
    { value: "arrow-narrow-right", label: "arrow-narrow-right" },
    { value: "at-sign", label: "at-sign" },
    { value: "bookmark-add", label: "bookmark-add" },
    { value: "bookmark-check", label: "bookmark-check" },
    { value: "building-large", label: "building-large" },
    { value: "building", label: "building" },
    { value: "calendar", label: "calendar" },
    { value: "check-circle-broken", label: "check-circle-broken" },
    { value: "check-circle", label: "check-circle" },
    { value: "check-heart", label: "check-heart" },
    { value: "check-square-broken", label: "check-square-broken" },
    { value: "check-square", label: "check-square" },
    { value: "check", label: "check" },
    { value: "chevron-down", label: "chevron-down" },
    { value: "chevron-left", label: "chevron-left" },
    { value: "chevron-right", label: "chevron-right" },
    { value: "chevron-selector-vertical", label: "chevron-selector-vertical" },
    { value: "chevron-up", label: "chevron-up" },
    { value: "clock", label: "clock" },
    { value: "cloud-blank", label: "cloud-blank" },
    { value: "credit-card", label: "credit-card" },
    { value: "currency-dollar-circle", label: "currency-dollar-circle" },
    { value: "face-happy", label: "face-happy" },
    { value: "face-neutral", label: "face-neutral" },
    { value: "face-sad", label: "face-sad" },
    { value: "face-smile", label: "face-smile" },
    { value: "globe", label: "globe" },
    { value: "heart-hand", label: "heart-hand" },
    { value: "heart", label: "heart" },
    { value: "help-circle", label: "help-circle" },
    { value: "home", label: "home" },
    { value: "image", label: "image" },
    { value: "info-circle", label: "info-circle" },
    { value: "lock", label: "lock" },
    { value: "marker-pin", label: "marker-pin" },
    { value: "menu", label: "menu" },
    { value: "minus-circle", label: "minus-circle" },
    { value: "minus-square", label: "minus-square" },
    { value: "minus", label: "minus" },
    { value: "percent-circle", label: "percent-circle" },
    { value: "percent", label: "percent" },
    { value: "pin", label: "pin" },
    { value: "plane", label: "plane" },
    { value: "plus-circle", label: "plus-circle" },
    { value: "plus-square", label: "plus-square" },
    { value: "plus", label: "plus" },
    { value: "puzzle-piece", label: "puzzle-piece" },
    { value: "rocket", label: "rocket" },
    { value: "search", label: "search" },
    { value: "share", label: "share" },
    { value: "shopping-bag", label: "shopping-bag" },
    { value: "shopping-cart", label: "shopping-cart" },
    { value: "star", label: "star" },
    { value: "tag", label: "tag" },
    { value: "thumbs-up", label: "thumbs-up" },
    { value: "tool", label: "tool" },
    { value: "truck", label: "truck" },
    { value: "user", label: "user" },
    { value: "x-circle", label: "x-circle" },
    { value: "x-close", label: "x-close" },
    { value: "zap", label: "zap" },
  ],
};
